- name: Enable third party repos
  become: yes
  become_user: root
  become_method: sudo
  dnf:
    name: fedora-workstation-repositories
    state: present

- name: Install brave browser
  block:
  - name: Install dnf plugins core
    become: yes
    become_user: root
    become_method: sudo
    dnf:
      name: dnf-plugins-core
      state: present

  - name: Add brave repo to config manager
    become: yes
    become_user: root
    become_method: sudo
    command: 
      cmd: dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/
      warn: false
    args:
      creates: /etc/yum.repos.d/brave-browser-rpm-release.s3.brave.com_x86_64_.repo

  - name: Import brave repo key
    become: yes
    become_user: root
    become_method: sudo
    rpm_key:
      state: present
      key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

  - name: Install Brave package
    become: yes
    become_user: root
    become_method: sudo
    dnf:
      name: brave-browser
      state: present

- name: Install lazygit
  block:
  - name: Enable lazygit COPR repo
    become: yes
    become_user: root
    become_method: sudo
    community.general.copr:
      name: atim/lazygit
      state: enabled

  - name: Install lazygit package
    become: yes
    become_user: root
    become_method: sudo
    dnf:
      name: lazygit
      state: present

  - name: Add lazygit alias to bashrc
    lineinfile:
      path: "{{ lookup('env', 'HOME') }}/.bashrc"
      line: "alias lg=lazygit"
      state: present

- name: Enable appindicators for gnome
  block:
    - name: Install the appindicator extension
      become: yes
      become_user: root
      become_method: sudo
      dnf:
        name: gnome-shell-extension-appindicator
        state: present

    - name: Check if appindicator enabled
      command: gsettings get org.gnome.shell enabled-extensions
      register: appindicators_info

    - name: Enable the appindicator extension
      command: gnome-extensions enable appindicatorsupport@rgcjonas.gmail.com
      when: "'appindicatorsupport' not in appindicators_info.stdout"

- name: Install default dnf packages
  become: yes
  become_user: root
  become_method: sudo
  dnf:
    name: "{{ item }}"
    state: present
  loop: "{{ packages }}"
