- name: Enable third party repos
  dnf:
    name: 
      - fedora-workstation-repositories

- name: Enable flathub
  command: flatpak remote-add --if-not-exists flathub https://flathub.org/repo/flathub.flatpakrepo

- name: Enable neovim-nightly COPR repo
  community.general.copr:
    name: agriffis/neovim-nightly

- name: Install dnf plugins core
  dnf:
    name: dnf-plugins-core

- name: Add brave repo to config manager
  command: dnf config-manager --add-repo https://brave-browser-rpm-release.s3.brave.com/x86_64/

- name: Import brave repo key
  command: rpm --import https://brave-browser-rpm-release.s3.brave.com/brave-core.asc
  
- name: Install dnf packages
  dnf:
    name: "{{ item }}"
  loop: "{{ packages }}"
