- name: Install global npm packages
  community.general.npm:
    name: "{{ item }}"
    state: present
    global: yes
  # become: yes
  # become_user: root
  # become_method: sudo
  loop: "{{ packages }}"
