[editor]
scrolloff = 1
line-number = "relative"

[editor.lsp]
auto-signature-help = false

[editor.file-picker]
hidden = false

[editor.indent-guides]
render = true

[keys.insert]
"A-x" = "signature_help"

[keys.normal]
"{" = "goto_prev_paragraph"
"}" = "goto_next_paragraph"
