- name: Add the flathub flatpak repository if needed
  community.general.flatpak_remote:
    name: flathub
    state: present
    flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
  become: yes
  become_user: root
  become_method: sudo

- name: Install flatpak packages
  community.general.flatpak:
    name: "{{ item }}"
    state: present
  become: yes
  become_user: root
  become_method: sudo
  loop: "{{ packages }}"
